// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlataformaAutogestion.Infrastructure.Data;

#nullable disable

namespace PlataformaAutogestion.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260605153338_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cuit")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateHigh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParameterSystem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Companys");
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.DetailLiquidation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<int>("IdLiquidation")
                        .HasColumnType("integer");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<int>("LiquidationId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalHours")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("amount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LiquidationId");

                    b.HasIndex("UserId");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.Liquidation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LiquidationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Liquidations");
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.Workday", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateApproval")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateEntry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("HoursWorked")
                        .HasColumnType("integer");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Workdays");
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.DetailLiquidation", b =>
                {
                    b.HasOne("PlataformaAutogestion.Domain.Entities.Company", "Company")
                        .WithMany("detailLiquidations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaAutogestion.Domain.Entities.Liquidation", "Liquidation")
                        .WithMany("detailLiquidations")
                        .HasForeignKey("LiquidationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaAutogestion.Domain.Entities.User", "User")
                        .WithMany("detailLiquidations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Liquidation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.Liquidation", b =>
                {
                    b.HasOne("PlataformaAutogestion.Domain.Entities.Company", "Company")
                        .WithMany("liquidations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.User", b =>
                {
                    b.HasOne("PlataformaAutogestion.Domain.Entities.Company", "Company")
                        .WithMany("users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.Workday", b =>
                {
                    b.HasOne("PlataformaAutogestion.Domain.Entities.Company", "Company")
                        .WithMany("workdays")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaAutogestion.Domain.Entities.User", "Usuario")
                        .WithMany("workdays")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.Company", b =>
                {
                    b.Navigation("detailLiquidations");

                    b.Navigation("liquidations");

                    b.Navigation("users");

                    b.Navigation("workdays");
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.Liquidation", b =>
                {
                    b.Navigation("detailLiquidations");
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.User", b =>
                {
                    b.Navigation("detailLiquidations");

                    b.Navigation("workdays");
                });
#pragma warning restore 612, 618
        }
    }
}
