// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlataformaAutogestion.Infrastructure.Data;

#nullable disable

namespace PlataformaAutogestion.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260618171058_FixInDetail")]
    partial class FixInDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Cuit")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateHigh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("ParameterSystem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Companys", (string)null);
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.DetailLiquidation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<int>("IdLiquidation")
                        .HasColumnType("integer");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.HasIndex("IdLiquidation");

                    b.HasIndex("IdUser");

                    b.ToTable("Details", (string)null);
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.Liquidation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LiquidationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("Liquidations", (string)null);
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.Workday", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DateApproval")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateEntry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("HoursWorked")
                        .HasColumnType("integer");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.HasIndex("IdUser");

                    b.ToTable("Workdays", (string)null);
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.DetailLiquidation", b =>
                {
                    b.HasOne("PlataformaAutogestion.Domain.Entities.Company", "Company")
                        .WithMany("detailLiquidations")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PlataformaAutogestion.Domain.Entities.Liquidation", "Liquidation")
                        .WithMany("detailLiquidations")
                        .HasForeignKey("IdLiquidation")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PlataformaAutogestion.Domain.Entities.User", "User")
                        .WithMany("detailLiquidations")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Liquidation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.Liquidation", b =>
                {
                    b.HasOne("PlataformaAutogestion.Domain.Entities.Company", "Company")
                        .WithMany("liquidations")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.User", b =>
                {
                    b.HasOne("PlataformaAutogestion.Domain.Entities.Company", "Company")
                        .WithMany("users")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.Workday", b =>
                {
                    b.HasOne("PlataformaAutogestion.Domain.Entities.Company", "Company")
                        .WithMany("workdays")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PlataformaAutogestion.Domain.Entities.User", "Usuario")
                        .WithMany("workdays")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.Company", b =>
                {
                    b.Navigation("detailLiquidations");

                    b.Navigation("liquidations");

                    b.Navigation("users");

                    b.Navigation("workdays");
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.Liquidation", b =>
                {
                    b.Navigation("detailLiquidations");
                });

            modelBuilder.Entity("PlataformaAutogestion.Domain.Entities.User", b =>
                {
                    b.Navigation("detailLiquidations");

                    b.Navigation("workdays");
                });
#pragma warning restore 612, 618
        }
    }
}
